# Generated by Django 2.1.5 on 2019-01-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderedcms', '0006_auto_20190108_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='layoutsettings',
            name='navbar_logo_style',
            field=models.CharField(blank=True, help_text='Custom style applied to navbar, use ";" to seperate.', max_length=255, verbose_name='Navbar Logo Style'),
        ),
    ]
